INSERT INTO `bamazon`.`department` (`dept_id`,`dept_name`,`over_head`) VALUES ('1','Clothings and Accessories','4000.5000');
INSERT INTO `bamazon`.`department` (`dept_id`,`dept_name`,`over_head`) VALUES ('2','Books','2018.9900');
INSERT INTO `bamazon`.`department` (`dept_id`,`dept_name`,`over_head`) VALUES ('3','Movies and Music','1168.0000');
INSERT INTO `bamazon`.`department` (`dept_id`,`dept_name`,`over_head`) VALUES ('4','Electronics','4406.7798');
INSERT INTO `bamazon`.`department` (`dept_id`,`dept_name`,`over_head`) VALUES ('5','Pet Supplies','2348.4500');
INSERT INTO `bamazon`.`department` (`dept_id`,`dept_name`,`over_head`) VALUES ('6','Toys','4383.7798');
INSERT INTO `bamazon`.`department` (`dept_id`,`dept_name`,`over_head`) VALUES ('7','Sports and Outdoors','2023.6500');
INSERT INTO `bamazon`.`department` (`dept_id`,`dept_name`,`over_head`) VALUES ('8','Outdoor Wear','2020.9301');
INSERT INTO `bamazon`.`department` (`dept_id`,`dept_name`,`over_head`) VALUES ('9','Appliance','3200.4500');
INSERT INTO `bamazon`.`products` (`item_id`,`product_name`,`price`,`stock_quantity`,`dept_ID`,`product_sales`) VALUES ('1','Days of Wonder Ticket to Ride','34.9900','13','6','68.9900');
INSERT INTO `bamazon`.`products` (`item_id`,`product_name`,`price`,`stock_quantity`,`dept_ID`,`product_sales`) VALUES ('2','EVOKE Navato 100 Sit in Recreational Kayak','519.0100','2','7','15040.5596');
INSERT INTO `bamazon`.`products` (`item_id`,`product_name`,`price`,`stock_quantity`,`dept_ID`,`product_sales`) VALUES ('3','Bulova Watch','80.9900','12','1','809.9000');
INSERT INTO `bamazon`.`products` (`item_id`,`product_name`,`price`,`stock_quantity`,`dept_ID`,`product_sales`) VALUES ('4','Long Sleeve Dress with Pockets','20.3900','16','1','1500.0000');
INSERT INTO `bamazon`.`products` (`item_id`,`product_name`,`price`,`stock_quantity`,`dept_ID`,`product_sales`) VALUES ('5','Full Moon by Jim Butcher','4.9900','20','2','200.0000');
INSERT INTO `bamazon`.`products` (`item_id`,`product_name`,`price`,`stock_quantity`,`dept_ID`,`product_sales`) VALUES ('6','Smoke Bitten by Patricia Briggs','13.9900','29','2','3500.0000');
INSERT INTO `bamazon`.`products` (`item_id`,`product_name`,`price`,`stock_quantity`,`dept_ID`,`product_sales`) VALUES ('7','John Wick: Chapter 3','19.9600','4','3','199.6000');
INSERT INTO `bamazon`.`products` (`item_id`,`product_name`,`price`,`stock_quantity`,`dept_ID`,`product_sales`) VALUES ('8','Spider-Man: Far from Home','22.9600','14','3','366.7600');
INSERT INTO `bamazon`.`products` (`item_id`,`product_name`,`price`,`stock_quantity`,`dept_ID`,`product_sales`) VALUES ('9','God of Ward -Playstation 4','25.9900','7','4','4500.0000');
INSERT INTO `bamazon`.`products` (`item_id`,`product_name`,`price`,`stock_quantity`,`dept_ID`,`product_sales`) VALUES ('10','Monster Hunter-Iceborne -Xbox One','49.9900','34','4','300.0000');
INSERT INTO `bamazon`.`products` (`item_id`,`product_name`,`price`,`stock_quantity`,`dept_ID`,`product_sales`) VALUES ('11','Control -Playstation 4','50.9400','32','4','1200.0000');
INSERT INTO `bamazon`.`products` (`item_id`,`product_name`,`price`,`stock_quantity`,`dept_ID`,`product_sales`) VALUES ('12','Pet Water Fountain -1.6L','18.3200','13','5','1300.0000');
INSERT INTO `bamazon`.`products` (`item_id`,`product_name`,`price`,`stock_quantity`,`dept_ID`,`product_sales`) VALUES ('13','Pacific Pups Products - Rope Toys -Agressive Chewers','18.6900','32','5','450.7800');
INSERT INTO `bamazon`.`products` (`item_id`,`product_name`,`price`,`stock_quantity`,`dept_ID`,`product_sales`) VALUES ('14','BackPack','65.7700','200','8','425.0000');
INSERT INTO `bamazon`.`products` (`item_id`,`product_name`,`price`,`stock_quantity`,`dept_ID`,`product_sales`) VALUES ('17','Water Bottle 116oz','23.5500','300','7','375.0000');